# Generated by Django 4.0 on 2021-12-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalinka_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='f_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
