# Generated by Django 4.0 on 2021-12-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalinka_app', '0002_alter_tarea_descripcion_alter_tarea_f_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='f_cierre',
            field=models.DateField(blank=True, null=True),
        ),
    ]
