# Generated by Django 4.0 on 2022-01-10 22:27

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kalinka_app', '0003_alter_tarea_f_cierre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kalinka_app.estado'),
        ),
    ]
