# Generated by Django 4.0 on 2022-02-21 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('kalinka_app', '0004_alter_tarea_color_alter_tarea_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='prioridad',
            name='creador',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
