# Generated by Django 4.0 on 2022-02-22 01:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalinka_app', '0006_alter_prioridad_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='prioridad',
            name='valor',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
