# Generated by Django 4.0 on 2022-03-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalinka_app', '0007_prioridad_valor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prioridad',
            options={'ordering': ['valor'], 'verbose_name': 'prioridad', 'verbose_name_plural': 'prioridades'},
        ),
    ]
