version: '3.8'
services:
    pgdb:
        image: postgres
        container_name: pgdb
        environment:
            - POSTGRES_DB=kalinka
            - POSTGRES_USER=kalinka
            - POSTGRES_PASSWORD=kalinka
        volumes:
            - pgdata:/var/lib/postgresql/data
    kalinka:
        build: .
        container_name: kalinka_app
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        depends_on:
            - pgdb

volumes:
    pgdata: 